Repository Link-Cargo/link-cargo-back, pull requests merged in 2024-08, with the labels that each got.

#18 Feat: 화물 정보에 수입,수출항 정보 사용, 반환 정보 수정
  src/main/java/com/example/linkcargo/domain/cargo/Cargo.java
  src/main/java/com/example/linkcargo/domain/cargo/CargoController.java
  src/main/java/com/example/linkcargo/domain/cargo/CargoService.java
  src/main/java/com/example/linkcargo/domain/cargo/dto/CargoDTO.java
  src/main/java/com/example/linkcargo/domain/cargo/dto/request/CargoRequest.java
  src/main/java/com/example/linkcargo/domain/cargo/dto/response/CargoPageResponse.java
  src/main/java/com/example/linkcargo/domain/cargo/dto/response/CargoResponse.java
  src/main/java/com/example/linkcargo/domain/cargo/dto/response/CargosResponse.java
  src/main/java/com/example/linkcargo/domain/token/dto/request/UserLoginRequest.java
  src/main/java/com/example/linkcargo/global/data/DataLoader.java
Labels: enhancement

#20 feat: 화물 여러 개 추가 기능
  src/main/java/com/example/linkcargo/domain/cargo/CargoController.java
  src/main/java/com/example/linkcargo/domain/cargo/CargoService.java
Labels: enhancement

#26 feat: 항구 CRUD
  src/main/java/com/example/linkcargo/domain/port/PortController.java
  src/main/java/com/example/linkcargo/domain/port/PortRepository.java
  src/main/java/com/example/linkcargo/domain/port/PortService.java
  src/main/java/com/example/linkcargo/domain/port/dto/request/PortCreateUpdateRequest.java
  src/main/java/com/example/linkcargo/domain/port/dto/response/PortReadResponse.java
  src/main/java/com/example/linkcargo/global/response/code/resultCode/ErrorStatus.java
Labels: enhancement

#29 feat: quotation 생성
  src/main/java/com/example/linkcargo/domain/quotation/Quotation.java
  src/main/java/com/example/linkcargo/domain/quotation/QuotationController.java
  src/main/java/com/example/linkcargo/domain/quotation/QuotationRepository.java
  src/main/java/com/example/linkcargo/domain/quotation/QuotationService.java
  src/main/java/com/example/linkcargo/domain/quotation/QuotationStatus.java
  src/main/java/com/example/linkcargo/domain/quotation/dto/request/QuotationConsignorRequest.java
  src/main/java/com/example/linkcargo/global/response/code/resultCode/ErrorStatus.java
  src/main/java/com/example/linkcargo/global/response/exception/handler/QuotationHandler.java
Labels: enhancement

#32 refactor: 선박 스케줄을 여러개 조회 시 랜덤 이미지 url 반환 값 추가
  src/main/java/com/example/linkcargo/domain/image/ImageRepository.java
  src/main/java/com/example/linkcargo/domain/image/ImageService.java
  src/main/java/com/example/linkcargo/domain/schedule/ScheduleService.java
  src/main/java/com/example/linkcargo/domain/schedule/dto/response/ScheduleInfoResponse.java
  src/main/java/com/example/linkcargo/domain/schedule/dto/response/ScheduleListResponse.java
Labels: enhancement

#35 feat: PortType에 따른 Port 조회
  src/main/java/com/example/linkcargo/domain/port/PortController.java
  src/main/java/com/example/linkcargo/domain/port/PortRepository.java
  src/main/java/com/example/linkcargo/domain/port/PortService.java
Labels: enhancement

#36 refactor: 선박 스케줄 검색 API 파라미터 수정
  src/main/java/com/example/linkcargo/domain/schedule/ScheduleController.java
  src/main/java/com/example/linkcargo/domain/schedule/ScheduleRepository.java
  src/main/java/com/example/linkcargo/domain/schedule/ScheduleService.java
Labels: enhancement

#37 remove: 테스트 파일 삭제
  src/test/java/com/example/linkcargo/cargo/cargoRepositoryTest.java
  src/test/java/com/example/linkcargo/user/UserServiceTest.java
Labels: bug

#47 Refactor: 화물 입력 정보 - 피그마에 맞게 수정
  src/main/java/com/example/linkcargo/domain/cargo/Cargo.java
  src/main/java/com/example/linkcargo/domain/cargo/CargoController.java
  src/main/java/com/example/linkcargo/domain/cargo/CargoService.java
  src/main/java/com/example/linkcargo/domain/cargo/dto/CargoDTO.java
  src/main/java/com/example/linkcargo/domain/cargo/dto/request/CargoRequest.java
  src/main/java/com/example/linkcargo/domain/cargo/dto/request/CargosRequest.java
Labels: enhancement

#49 feat: 포워더/알고리즘에 의한 견적서 업데이트
  src/main/java/com/example/linkcargo/domain/quotation/Quotation.java
  src/main/java/com/example/linkcargo/domain/quotation/QuotationCalculationService.java
  src/main/java/com/example/linkcargo/domain/quotation/QuotationController.java
  src/main/java/com/example/linkcargo/domain/quotation/QuotationRepository.java
  src/main/java/com/example/linkcargo/domain/quotation/QuotationService.java
  src/main/java/com/example/linkcargo/domain/quotation/QuotationStatus.java
  src/main/java/com/example/linkcargo/domain/quotation/dto/request/QuotationConsignorRequest.java
  src/main/java/com/example/linkcargo/domain/quotation/dto/request/QuotationForwarderRequest.java
  src/main/java/com/example/linkcargo/global/config/GlobalConfig.java
  src/main/java/com/example/linkcargo/global/response/code/resultCode/ErrorStatus.java
Labels: enhancement

#50 refactor: schedule api 변경 사항 업데이트
  src/main/java/com/example/linkcargo/domain/schedule/Schedule.java
  src/main/java/com/example/linkcargo/domain/schedule/ScheduleController.java
  src/main/java/com/example/linkcargo/domain/schedule/ScheduleRepository.java
  src/main/java/com/example/linkcargo/domain/schedule/ScheduleService.java
  src/main/java/com/example/linkcargo/domain/schedule/dto/request/ScheduleCreateUpdateRequest.java
Labels: enhancement

#51 feat: 포워딩 CRUD
  src/main/java/com/example/linkcargo/domain/forwarding/Forwarding.java
  src/main/java/com/example/linkcargo/domain/forwarding/ForwardingController.java
  src/main/java/com/example/linkcargo/domain/forwarding/ForwardingRepository.java
  src/main/java/com/example/linkcargo/domain/forwarding/ForwardingService.java
  src/main/java/com/example/linkcargo/domain/forwarding/dto/request/ForwardingCreateUpdateRequest.java
  src/main/java/com/example/linkcargo/domain/forwarding/dto/response/ForwardingInfoResponse.java
  src/main/java/com/example/linkcargo/global/response/code/resultCode/ErrorStatus.java
  src/main/java/com/example/linkcargo/global/response/exception/handler/ForwardingHandler.java
Labels: enhancement

#53 refactor: 포워더 견적서 업데이트 시 특이사항 작성 추가
  src/main/java/com/example/linkcargo/domain/quotation/dto/request/QuotationConsignorRequest.java
  src/main/java/com/example/linkcargo/domain/quotation/dto/request/QuotationForwarderRequest.java
Labels: enhancement

#54 feat: 대시보드 화면 (1)
  build.gradle
  src/main/java/com/example/linkcargo/domain/dashboard/DashboardController.java
  src/main/java/com/example/linkcargo/domain/dashboard/DashboardService.java
  src/main/java/com/example/linkcargo/domain/dashboard/dto/response/DashboardPredictionReasonResponse.java
  src/main/java/com/example/linkcargo/domain/dashboard/dto/response/DashboardPredictionResponse.java
  src/main/java/com/example/linkcargo/domain/dashboard/dto/response/DashboardQuotationCompareResponse.java
  src/main/java/com/example/linkcargo/domain/dashboard/dto/response/DashboardQuotationResponse.java
  src/main/java/com/example/linkcargo/domain/prediction/Prediction.java
  src/main/java/com/example/linkcargo/domain/prediction/PredictionRepository.java
  src/main/java/com/example/linkcargo/domain/quotation/QuotationCalculationService.java
  src/main/java/com/example/linkcargo/domain/quotation/QuotationController.java
  src/main/java/com/example/linkcargo/domain/quotation/QuotationRepository.java
  src/main/java/com/example/linkcargo/domain/quotation/dto/response/QuotationInfoResponse.java
  src/main/java/com/example/linkcargo/global/config/GlobalConfig.java
Labels: enhancement, EPIC

#56 feat: 사용자 정보(프로필 이미지 포함) 조회, 수정
  src/main/java/com/example/linkcargo/domain/chat/ChatRestController.java
  src/main/java/com/example/linkcargo/domain/test/testController.java
  src/main/java/com/example/linkcargo/domain/token/dto/request/UserRegisterRequest.java
  src/main/java/com/example/linkcargo/domain/user/User.java
  src/main/java/com/example/linkcargo/domain/user/UserController.java
  src/main/java/com/example/linkcargo/domain/user/UserS3Service.java
  src/main/java/com/example/linkcargo/domain/user/UserService.java
  src/main/java/com/example/linkcargo/domain/user/dto/UserDTO.java
  src/main/java/com/example/linkcargo/domain/user/dto/request/UserPasswordUpdateRequest.java
  src/main/java/com/example/linkcargo/domain/user/dto/response/FileResponse.java
  src/main/java/com/example/linkcargo/domain/user/dto/response/UserResponse.java
  src/main/java/com/example/linkcargo/global/response/code/resultCode/ErrorStatus.java
Labels: enhancement

#57 feat: 사용자 정보(프로필 이미지 포함) 조회, 수정
  src/main/java/com/example/linkcargo/domain/chat/ChatRestController.java
  src/main/java/com/example/linkcargo/domain/test/testController.java
  src/main/java/com/example/linkcargo/domain/token/dto/request/UserRegisterRequest.java
  src/main/java/com/example/linkcargo/domain/user/User.java
  src/main/java/com/example/linkcargo/domain/user/UserController.java
  src/main/java/com/example/linkcargo/domain/user/UserS3Service.java
  src/main/java/com/example/linkcargo/domain/user/UserService.java
  src/main/java/com/example/linkcargo/domain/user/dto/UserDTO.java
  src/main/java/com/example/linkcargo/domain/user/dto/request/UserPasswordUpdateRequest.java
  src/main/java/com/example/linkcargo/domain/user/dto/response/FileResponse.java
  src/main/java/com/example/linkcargo/domain/user/dto/response/UserResponse.java
  src/main/java/com/example/linkcargo/global/response/code/resultCode/ErrorStatus.java
Labels: enhancement

#58 fix: 테스트 파일 삭제
  src/main/java/com/example/linkcargo/domain/chat/ChatService.java
  src/main/java/com/example/linkcargo/domain/chat/ChatStompController.java
  src/main/java/com/example/linkcargo/domain/chat/Entity/Chat.java
  src/main/java/com/example/linkcargo/domain/chat/dto/request/ChatRequest.java
  src/main/java/com/example/linkcargo/domain/chat/dto/response/ChatContentResponse.java
  src/main/java/com/example/linkcargo/domain/chat/dto/response/ChatEnterResponse.java
  src/test/java/com/example/linkcargo/LinkcargoApplicationTests.java
  src/test/java/com/example/linkcargo/chat/WebSocketTest.java
Labels: enhancement

#59 Feat: 채팅 API 기타 부분 수정
  src/main/java/com/example/linkcargo/domain/chat/ChatRestController.java
  src/main/java/com/example/linkcargo/global/data/DataLoader.java
Labels: enhancement

#61 feat: 대시보드 API (2)
  src/main/java/com/example/linkcargo/domain/dashboard/DashboardController.java
  src/main/java/com/example/linkcargo/domain/dashboard/DashboardService.java
  src/main/java/com/example/linkcargo/domain/dashboard/dto/response/DashboardNewsResponse.java
  src/main/java/com/example/linkcargo/domain/dashboard/dto/response/DashboardPortCongestionResponse.java
  src/main/java/com/example/linkcargo/domain/dashboard/dto/response/DashboardRecommendationResponse.java
  src/main/java/com/example/linkcargo/domain/news/NewsRepository.java
  src/main/java/com/example/linkcargo/domain/prediction/PredictionRepository.java
  src/main/java/com/example/linkcargo/domain/quotation/QuotationCalculationService.java
  src/main/java/com/example/linkcargo/domain/quotation/QuotationRepository.java
  src/main/java/com/example/linkcargo/domain/schedule/ScheduleRepository.java
Labels: enhancement, EPIC

#63 refactor: Quotation 관련 변경
  src/main/java/com/example/linkcargo/domain/dashboard/DashboardController.java
  src/main/java/com/example/linkcargo/domain/dashboard/DashboardService.java
  src/main/java/com/example/linkcargo/domain/quotation/Quotation.java
  src/main/java/com/example/linkcargo/domain/quotation/QuotationCalculationService.java
  src/main/java/com/example/linkcargo/domain/quotation/QuotationController.java
  src/main/java/com/example/linkcargo/domain/quotation/QuotationRepository.java
  src/main/java/com/example/linkcargo/domain/quotation/QuotationService.java
  src/main/java/com/example/linkcargo/domain/quotation/dto/request/QuotationConsignorRequest.java
  src/main/java/com/example/linkcargo/domain/quotation/dto/request/QuotationForwarderRequest.java
  src/main/java/com/example/linkcargo/domain/quotation/dto/response/QuotationInfoResponse.java
Labels: enhancement

#65 Feat: 화물 입력 데이터 및 저장 후 반환 데이터 수정
  src/main/java/com/example/linkcargo/domain/cargo/Cargo.java
  src/main/java/com/example/linkcargo/domain/cargo/CargoController.java
  src/main/java/com/example/linkcargo/domain/cargo/CargoService.java
  src/main/java/com/example/linkcargo/domain/cargo/dto/CargoDTO.java
  src/main/java/com/example/linkcargo/domain/cargo/dto/request/CargoRequest.java
  src/main/java/com/example/linkcargo/domain/cargo/dto/response/CargoIdsResponse.java
Labels: enhancement

#66 Feat: 화물 정보 입력 데이터 및 저장 후 반환 데이터 수정
  src/main/java/com/example/linkcargo/domain/cargo/Cargo.java
  src/main/java/com/example/linkcargo/domain/cargo/CargoController.java
  src/main/java/com/example/linkcargo/domain/cargo/CargoService.java
  src/main/java/com/example/linkcargo/domain/cargo/dto/CargoDTO.java
  src/main/java/com/example/linkcargo/domain/cargo/dto/request/CargoRequest.java
  src/main/java/com/example/linkcargo/domain/cargo/dto/response/CargoIdsResponse.java
Labels: enhancement

#68 Feat: 알림 전송 기능
  .gitignore
  build.gradle
  src/main/java/com/example/linkcargo/domain/fcmToken/FCMToken.java
  src/main/java/com/example/linkcargo/domain/fcmToken/FCMTokenController.java
  src/main/java/com/example/linkcargo/domain/fcmToken/FCMTokenRepository.java
  src/main/java/com/example/linkcargo/domain/fcmToken/FCMTokenService.java
  src/main/java/com/example/linkcargo/domain/fcmToken/dto/FCMTokenRequest.java
  src/main/java/com/example/linkcargo/domain/notification/Notification.java
  src/main/java/com/example/linkcargo/domain/notification/NotificationController.java
  src/main/java/com/example/linkcargo/domain/notification/NotificationRepository.java
  src/main/java/com/example/linkcargo/domain/notification/NotificationService.java
  src/main/java/com/example/linkcargo/domain/notification/dto/NotificationDTO.java
  src/main/java/com/example/linkcargo/domain/notification/dto/response/NotificationPageResponse.java
  src/main/java/com/example/linkcargo/domain/notification/dto/response/NotificationsResponse.java
  src/main/java/com/example/linkcargo/global/config/FirebaseConfig.java
  src/main/java/com/example/linkcargo/global/response/code/resultCode/ErrorStatus.java
  src/main/java/com/example/linkcargo/global/response/exception/handler/FCMTokenHandler.java
  src/main/java/com/example/linkcargo/global/response/exception/handler/NotificationHandler.java
Labels: enhancement

#69 Feat: 알림 전송 기능
  .gitignore
  build.gradle
  src/main/java/com/example/linkcargo/domain/fcmToken/FCMToken.java
  src/main/java/com/example/linkcargo/domain/fcmToken/FCMTokenController.java
  src/main/java/com/example/linkcargo/domain/fcmToken/FCMTokenRepository.java
  src/main/java/com/example/linkcargo/domain/fcmToken/FCMTokenService.java
  src/main/java/com/example/linkcargo/domain/fcmToken/dto/FCMTokenRequest.java
  src/main/java/com/example/linkcargo/domain/notification/Notification.java
  src/main/java/com/example/linkcargo/domain/notification/NotificationController.java
  src/main/java/com/example/linkcargo/domain/notification/NotificationRepository.java
  src/main/java/com/example/linkcargo/domain/notification/NotificationService.java
  src/main/java/com/example/linkcargo/domain/notification/dto/NotificationDTO.java
  src/main/java/com/example/linkcargo/domain/notification/dto/response/NotificationPageResponse.java
  src/main/java/com/example/linkcargo/domain/notification/dto/response/NotificationsResponse.java
  src/main/java/com/example/linkcargo/global/config/FirebaseConfig.java
  src/main/java/com/example/linkcargo/global/response/code/resultCode/ErrorStatus.java
  src/main/java/com/example/linkcargo/global/response/exception/handler/FCMTokenHandler.java
  src/main/java/com/example/linkcargo/global/response/exception/handler/NotificationHandler.java
Labels: enhancement
